server:
  port: 8081

spring:
  profiles:
    active: dev
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  data:
    mongodb:
      database: hotel-room-reservation

logging:
  level: info


security:
  basic:
    enabled: false