server:
  port: 8081

spring:
  profiles:
    active: dev, security
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  data:
    mongodb:
      database: hotel-room-reservation

logging:
  level: info

---
spring:
  profiles: no-security
security:
  basic:
    enabled: false